package forge.engine;

import forge.event.MarketEventOccurrence;
import forge.feature.SessionRangeFeature;
import forge.statistics.StatisticsService;
import forge.study.MarketStudy;
import forge.study.StudyCatalog;

import java.util.Collection;
import java.util.List;

public class QueryService {
    private final StudyCatalog studyCatalog;
    private final StatisticsService statisticsService;

    public QueryService() {
        /*
         * Intent: Create the query service with default study catalog and statistics service.
         * Precondition: Default study/statistics dependencies must be available.
         * Returns: A constructed QueryService instance.
         * Postcondition: Service can summarize supported market studies.
         */
        this(new StudyCatalog(), new StatisticsService());
    }

    public QueryService(StudyCatalog studyCatalog, StatisticsService statisticsService) {
        /*
         * Intent: Create the query service with explicit study and statistics dependencies.
         * Precondition: Study catalog and statistics service must be non-null.
         * Returns: A constructed QueryService instance.
         * Postcondition: Query metadata and summaries delegate to supplied dependencies.
         */
        if (studyCatalog == null) {
            throw new IllegalArgumentException("studyCatalog is required");
        }
        if (statisticsService == null) {
            throw new IllegalArgumentException("statisticsService is required");
        }
        this.studyCatalog = studyCatalog;
        this.statisticsService = statisticsService;
    }

    public List<String> getSupportedQueryEventNames() {
        /*
         * Intent: Expose market study/event names available for statistics queries.
         * Precondition: Study catalog must be configured.
         * Returns: List of supported study names.
         * Postcondition: Service state is unchanged.
         */
        return studyCatalog.findAvailableStudyNames();
    }

    public String getEventStatisticDisplayName(String eventName) {
        return studyCatalog.getStudy(eventName).getDisplayName();
    }

    public String getEventStatisticDescription(String eventName) {
        return studyCatalog.getStudy(eventName).getDescription();
    }

    public EventStatisticsReport summarizeEventStatistics(
            EventStatisticsQuery query,
            Collection<SessionRangeFeature> sessionRangeFeatures,
            Collection<MarketEventOccurrence> events
    ) {
        /*
         * Intent: Convert derived features and condition occurrences into an event-statistics report.
         * Precondition: Query must identify a supported market study.
         * Returns: EventStatisticsReport generated by the statistics service.
         * Postcondition: Derived-data collections are read but not modified.
         */
        if (query == null) {
            throw new IllegalArgumentException("query is required");
        }
        MarketStudy study = studyCatalog.getStudy(query.getEventName());
        return statisticsService.summarizeStudyOccurrences(study, sessionRangeFeatures, events);
    }
}
