package forge.reporting;

public class FacadeForgeReporting {
    private static final FacadeForgeReporting THE_INSTANCE = new FacadeForgeReporting();

    private final ForgeReportingAccess access = new ForgeReportingAccess();

    public static FacadeForgeReporting getTheInstance() {
        return THE_INSTANCE;
    }

    public ForgeReportingAccess forgeReportingAccess() {
        return access;
    }

    public static class ForgeReportingAccess {
        /*
         * Intent: Create an empty placeholder backtest result through the reporting facade.
         * Precondition: None.
         * Returns: BacktestResult representing a not-yet-run backtest.
         * Postcondition: No shared reporting state is changed.
         */
        public BacktestResult createBacktestResult() {
            return new BacktestResult();
        }

        /*
         * Intent: Create a zeroed metrics object through the reporting facade.
         * Precondition: None.
         * Returns: Empty PerformanceMetrics instance.
         * Postcondition: No shared reporting state is changed.
         */
        public PerformanceMetrics createPerformanceMetrics() {
            return new PerformanceMetrics();
        }

        /*
         * Intent: Create the instrument performance report placeholder through the facade.
         * Precondition: None.
         * Returns: InstrumentPerformanceReport instance.
         * Postcondition: No shared reporting state is changed.
         */
        public InstrumentPerformanceReport createInstrumentPerformanceReport() {
            return new InstrumentPerformanceReport();
        }

        /*
         * Intent: Convert a backtest result into report text.
         * Precondition: result must be non-null.
         * Returns: Multi-line summary generated by the result.
         * Postcondition: Result state is unchanged.
         */
        public String summarize(BacktestResult result) {
            if (result == null) {
                throw new IllegalArgumentException("result is required");
            }
            return result.toString();
        }
    }
}
